### ISSUE TITLE
Incompatible with PUC Lua+luaffifb

### ISSUE THREAD

**Issue by alexbw** [torch/sdl2-ffi#7]
Works fine with LuaJIT 2.0, but no PUC Lua w/ luaffifb.
```
> require 'sdl2'
lua: ...rs/Alex/anaconda/envs/_test/share/lua/5.2/sdl2/cdefs.lua:201: attempt to index global 'jit' (a nil value)
stack traceback:
	...rs/Alex/anaconda/envs/_test/share/lua/5.2/sdl2/cdefs.lua:201: in main chunk
	[C]: in function 'require'
	/Users/Alex/anaconda/envs/_test/share/lua/5.2/sdl2/init.lua:9: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
``

**Comment by soumith** [comment]
Fixed via: https://github.com/torch/sdl2-ffi/commit/e3d861d543c51dc78c59399b5c1cf2142b7986c0

**Comment by alexbw** [comment]
Getting "Invalid Character" errors on the double brackets before and after `cdef`. Still builds in LuaJIT. Is this my problem, luaffi, or sdl's?

**Comment by alexbw** [comment]
```
+ lua -e 'require '\''sdl2'\'''
lua: ...ltschko/anaconda/envs/_test/share/lua/5.2/sdl2/cdefs.lua:2395: invalid character 10
stack traceback:
	[C]: in function 'cdef'
	...ltschko/anaconda/envs/_test/share/lua/5.2/sdl2/cdefs.lua:2395: in main chunk
	[C]: in function 'require'
	...iltschko/anaconda/envs/_test/share/lua/5.2/sdl2/init.lua:9: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
```

**Comment by alexbw** [comment]
@soumith still not fixed here, are you unable to replicate?

**Comment by soumith** [comment]
sorry, went on an impromptu vacation, just got back last week and have been catching up with tasks.
fixed this other issue, via https://github.com/torch/sdl2-ffi/commit/50659fbeca83d667240b197298a0462c7ec0ad21 and tested it in PUC Lua.
Opened a task in luaffifb for a permanent fix.
